### ISSUE TITLE
Demand System not produced

### ISSUE THREAD

**Issue by hanmhan** [weinih/eep153project4#6]
Code errors, did not produce a demand system

**Comment by weinih** [comment]
Can you point the special error?

**Comment by liandy52** [comment]
Where are the code errors at? Please specify.

**Comment by meiyinghuang** [comment]
> Code errors, did not produce a demand system

Hi Hanmhan, thanks for your feedback. We've added more descriptions perhaps it helps you find the Demand System.  :)
